In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.ndim# get a dimension

1

In [5]:
a.shape# to get shape

(3,)

In [14]:
a=np.array([1,2,3],dtype='int16')

In [7]:
a

array([1, 2, 3], dtype=int16)

In [11]:
a.dtype

dtype('int32')

In [12]:
a.itemsize

4

In [13]:
a.nbytes

12

In [15]:
a.nbytes

6

In [16]:
b=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [17]:
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# to get a specific element in [r,c]
b[1,5]


13

In [19]:
#to get a specific row
b[1:,]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [20]:
b[:,1]

array([2, 9])

In [22]:
b[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
b[:,1]

array([2, 9])

In [25]:
b[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
b[0,3]

4

In [29]:
b[0:,3]

array([ 4, 11])

In [30]:
b[0:,:4]

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [32]:
b[0:,1:3]

array([[ 2,  3],
       [ 9, 10]])

In [33]:
b[1,2]=20

In [34]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13, 14]])

In [35]:
b[:,2]

array([ 3, 20])

In [36]:
b[0:,1]

array([2, 9])

In [37]:
b[0:,:2]

array([[1, 2],
       [8, 9]])

In [43]:
b[0:,1]

array([2, 9])

In [45]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.full((2,3),67)

array([[67, 67, 67],
       [67, 67, 67]])

In [50]:
np.full_like(a,5)

array([5, 5, 5], dtype=int16)

In [51]:
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [55]:
#random decimal numbers(rows:columns:stepsize)
c=np.random.rand(4,2,2)

In [56]:
c

array([[[0.9159286 , 0.79433523],
        [0.52181506, 0.00551571]],

       [[0.79381954, 0.45399091],
        [0.07642242, 0.19214337]],

       [[0.1918085 , 0.28308812],
        [0.25870076, 0.37583284]],

       [[0.80690114, 0.02673242],
        [0.79293144, 0.68530624]]])

In [63]:
#random integer values
d=np.random.randint(3,size=(2,3))

In [64]:
d

array([[0, 2, 0],
       [1, 2, 2]])

In [65]:
np.identity(6)#the identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
#the transpose matrix
c.T

array([[[0.9159286 , 0.79381954, 0.1918085 , 0.80690114],
        [0.52181506, 0.07642242, 0.25870076, 0.79293144]],

       [[0.79433523, 0.45399091, 0.28308812, 0.02673242],
        [0.00551571, 0.19214337, 0.37583284, 0.68530624]]])

In [68]:
ar=np.array([1,2,3])
s1=np.repeat(ar,2)

In [69]:
ar

array([1, 2, 3])

In [70]:
s1

array([1, 1, 2, 2, 3, 3])

In [81]:
ar=np.array([[1,2,3]])
s1=np.repeat(ar,3,axis=0)
print(s1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
ar

array([[1, 2, 3]])

In [83]:
s1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [84]:
#linear algebra
a=np.ones((2,3))
b=np.full((3,2),2)

In [85]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [87]:
c=np.identity(3)

In [88]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.linalg.det(c)#to find the determinant

1.0

In [91]:
g=np.random.rand(3,4)

In [92]:
g

array([[0.83299545, 0.33054788, 0.00591398, 0.46528323],
       [0.41844176, 0.74598852, 0.70973325, 0.34575705],
       [0.73093909, 0.71354196, 0.01860753, 0.58128769]])

In [93]:
np.linalg.det(g)

LinAlgError: Last 2 dimensions of the array must be square

In [94]:
#statistics
a=np.array([[1,2,3],[3,4,5]])

In [95]:
np.min(a)

1

In [96]:
np.max(a)

5

In [97]:
np.sum(a)

18

In [99]:
np.sum(a,axis=1)

array([ 6, 12])

In [100]:
#reorganizing arrays
before=np.array([[1,2,3,4],[5,6,7,8]])

In [101]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
after=before.reshape(8,1)

In [105]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [106]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

In [108]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
np.vstack(v1)

array([[1],
       [2],
       [3],
       [4]])

In [112]:
#horizontal stacking
np.hstack(v1)

array([1, 2, 3, 4])

In [113]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
#load data from the file
df=np.genfromtxt('D:/data science with python/data.txt',delimiter=',')

In [117]:
df

array([1., 2., 3., 4., 5., 6.])