In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
n1=np.array([1,2,3])

In [3]:
n1

array([1, 2, 3])

In [4]:
l1=pd.Series([1,2,3])

In [5]:
l1

0    1
1    2
2    3
dtype: int64

In [6]:
l1.size

3

In [7]:
l=range(1000)

In [8]:
print(sys.getsizeof(5)*len(l))

28000


In [9]:
l2=np.arange(1000)

In [10]:
l2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [11]:
l2.size

1000

In [12]:
print(l2.size*l2.itemsize)

4000


In [13]:
n3=np.array([[1,2,5],[4,5,9]])

### 

In [14]:
n3

array([[1, 2, 5],
       [4, 5, 9]])

In [15]:
n3.ndim

2

In [16]:
n3.itemsize#itemsize represents size of each element in array

4

In [17]:
n3.size

6

In [18]:
n3.dtype

dtype('int32')

In [19]:
n4=np.array([[1,2],[3,4],[5,6]],dtype=np.float)

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_27688\859436938.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  n4=np.array([[1,2],[3,4],[5,6]],dtype=np.float)


In [20]:
n4

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [21]:
n4.itemsize

8

In [23]:
n5=np.zeros(2)

In [24]:
n5

array([0., 0.])

In [25]:
n5=np.zeros(3)

In [26]:
n5

array([0., 0., 0.])

In [28]:
n5=np.zeros((2,3))#put shape here

In [29]:
n5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
n6=np.ones((3,4))

In [31]:
n6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
n7=np.arange(3)

In [34]:
n7

array([0, 1, 2])

In [35]:
n8=np.arange(1,8)

In [36]:
n8

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
n9=np.arange(1,5,3)

In [38]:
n9

array([1, 4])

In [39]:
n10=np.linspace(1,5,3)

In [40]:
n10

array([1., 3., 5.])

In [42]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
n4.shape

(3, 2)

In [47]:
n4.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
n4

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [49]:
n4.ravel()

array([1., 2., 3., 4., 5., 6.])

In [50]:
n4.min()

1.0

In [51]:
n4.max()

6.0

In [52]:
n1=np.array((2,3)

SyntaxError: unexpected EOF while parsing (2743821446.py, line 1)

In [54]:
n1=np.array([[1,2],[3,4],[5,6]])

# 

In [55]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
n2=np.array([[2,3],[5,6],[7,8]])

In [57]:
n2

array([[2, 3],
       [5, 6],
       [7, 8]])

In [61]:
n4.sum(axis=0)

array([ 9., 12.])

In [59]:
n3=n1+n2

In [60]:
n3

array([[ 3,  5],
       [ 8, 10],
       [12, 14]])

In [62]:
n4.sum(axis=1)

array([ 3.,  7., 11.])

In [63]:
np.sqrt(n4)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [64]:
n4[0:2]

array([[1., 2.],
       [3., 4.]])

In [65]:
n4

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [66]:
n4[:1]

array([[1., 2.]])

In [67]:
n4[2:1]

array([], shape=(0, 2), dtype=float64)

In [68]:
n4[1:2]

array([[3., 4.]])

In [69]:
n4[:2]

array([[1., 2.],
       [3., 4.]])

In [70]:
n4[3:2]

array([], shape=(0, 2), dtype=float64)

In [71]:
n4[1:3]

array([[3., 4.],
       [5., 6.]])

In [73]:
n4[0,1:2]

array([2.])

In [74]:
n4[1,1:2]

array([4.])

In [75]:
n4[2,0:2]

array([5., 6.])

In [77]:
n4[1,0:2]

array([3., 4.])

In [80]:
np.hsplit(n4,3)

ValueError: array split does not result in an equal division

In [81]:
b=np.arange(20)

In [82]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
c=b.reshape(4,5)

In [91]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [97]:
j=c>4

In [98]:
j

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [99]:
for cell in c.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
